version: "3.9"

services:
  space-hosting:
    build:
      context: .
    ports:
    - "8080:8080"
    volumes:
    - ./.data:/data
    environment:
    - SH_INDEX_ALGORITHM=FaissIndex.Flat.L2
    - SH_VECTORS_FILE_NAME=/data/vectors-df.csv
    - SH_VECTORS_FILE_FORMAT=PandasDataFrameCsv
    - SH_VECTORS_METADATA_FILE_NAME=/data/vectors-metadata.json
