title: Vektonn

# social links
github_username:   # DO NOT include the @ character, or else the build will fail!

remote_theme: pmarsceill/just-the-docs

# just-the-docs theme configuration
color_scheme: nil
search_enabled: false
