title: Vektonn

# social links
github_username:   # DO NOT include the @ character, or else the build will fail!

remote_theme: pmarsceill/just-the-docs

# just-the-docs theme configuration
color_scheme: nil
markdown: kramdown
search_enabled: false
back_to_top: false
