name: CI

on:
  push:
    branches:
    - '**'
    tags:
    - 'v[0-9]+.[0-9]+-release*'
    paths:
    - 'src/**'

  pull_request:
    branches:
    - master
    paths:
    - 'src/**'

env:
  NUGET_PACKAGES_DIR: ${{ github.workspace }}/nuget-packages

jobs:
  build-pack-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./src
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack SpaceHosting.Contracts
      run: dotnet pack --configuration Release --no-build --output ${{ env.NUGET_PACKAGES_DIR }} ./SpaceHosting.Contracts/SpaceHosting.Contracts.csproj

    - name: Pack SpaceHosting.IndexShard
      run: dotnet pack --configuration Release --no-build --output ${{ env.NUGET_PACKAGES_DIR }} ./SpaceHosting.IndexShard/SpaceHosting.IndexShard.csproj

    - name: Store nuget packages as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: ${{ env.NUGET_PACKAGES_DIR }}/*
        if-no-files-found: error
        retention-days: 10

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

  nuget-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-pack-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Download nuget packages from artifacts
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
        path: ${{ env.NUGET_PACKAGES_DIR }}

    - name: Publish to nuget.org
      run: dotnet nuget push ${{ env.NUGET_PACKAGES_DIR }}/*.nupkg --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json
